apsi_innovations/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from apsi_innovations.views import users, admin_panel, activate_user, activate_committee, student_employee_profile

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('signup.urls')),
    path(r'innovations/', include('innovations.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'socials/', include('socials.urls')),
    path(r'users/', users, name='users'),
    path(r'admin_panel/', admin_panel, name='admin_panel'),
    path(r'activate_user/', activate_user, name='activate_user'),
    path(r'activate_committee/', activate_committee, name='activate_committee'),
    path('student_employee_profile/', student_employee_profile, name='student_employee_profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovations/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

from innovations.views import set_status, InnovationAddView, ReportViolationView, \
    reported_violations, finish_violation_report, rate, update_status, InnovationUpdateView, InnovationListView, \
    update_weights, vote_status, innovation_comment

urlpatterns = [
    path('', TemplateView.as_view(template_name="innovations/innovations_home.html")),
    path('innovations/', InnovationListView.as_view(), name='innovations'),
    path('add_innovation/', InnovationAddView.as_view(), name='add_innovation'),
    path('set_status/<int:id>/<str:status>/', set_status, name='set_status'),
    path('rate/<int:id>/', rate, name='rate'),
    path('report_violation/<int:id>', ReportViolationView.as_view(), name='report_violation'),
    path('reported_violations/', reported_violations, name='reported_violations'),
    path('finish_violation_report/', finish_violation_report, name='finish_violation_report'),
    path('details/<int:id>', views.details, name='details'),
    path('update_status/<int:id>', update_status, name='update_status'),
    path('vote_status/<int:id>/', vote_status, name='vote_status'),
    path('edit_innovation/<int:pk>', InnovationUpdateView.as_view(), name='edit_innovation'),
    path('update_weights/<int:id>/', update_weights, name='update_weights'),
    path('comment/<int:id>/', innovation_comment, name='innovation_comment'),
]

signup/urls.py
from django.contrib.auth.views import login
from django.urls import path

from signup.views import signup, home, account_inactive

urlpatterns = [
    path(r'', home, name='home'),
    path(r'account_inactive/', account_inactive, name='account_inactive'),
    path(r'login/', login, {'template_name': 'login.html'}, name='login'),
    path(r'signup/', signup, name='signup'),
]

innovations/models.py
import os

from django.contrib.auth.models import User
from django.db import models

from innovations.grades import calculate_innovation_grade


class Innovation(models.Model):
    class Status:
        ACCEPTED = 'accepted'
        BLOCKED = 'blocked'
        REJECTED = 'rejected'
        SUSPENDED = 'suspended'
        IN_REPLENISHMENT = 'in_replenishment'
        PENDING = 'pending'
        VOTING = 'voting'

    STATUS_CHOICES = (
        (Status.ACCEPTED, 'Accepted'),
        (Status.BLOCKED, 'Blocked'),
        (Status.REJECTED, 'Rejected'),
        (Status.SUSPENDED, 'Suspended'),
        (Status.IN_REPLENISHMENT, 'In Replenishment'),
        (Status.PENDING, 'Pending'),
        (Status.VOTING, 'Voting'),
    )

    subject = models.CharField(max_length=128)
    description = models.TextField(max_length=1024)
    assumptions = models.TextField(max_length=1024)
    benefits = models.CharField(max_length=1024)
    costs = models.CharField(max_length=1024)
    status = models.CharField(choices=STATUS_CHOICES, max_length=32, default=Status.PENDING)
    status_substantiation = models.CharField(max_length=1024, verbose_name='Status Substantiation', null=True)
    student_grade_weight = models.DecimalField(verbose_name="Student's Grade Weight", max_digits=3, decimal_places=2,
                                               default=1.0)
    employee_grade_weight = models.DecimalField(verbose_name="Employee's Grade Weight", max_digits=3, decimal_places=2,
                                                default=1.0)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Time Added')
    issuer = models.ForeignKey(User, related_name='innovations', on_delete=models.deletion.CASCADE)

    @property
    def grade(self):
        grades = Grade.objects.filter(innovation=self)
        return calculate_innovation_grade(grades)


class Keyword(models.Model):
    keyword = models.CharField(max_length=128)
    innovation = models.ForeignKey(Innovation, related_name='keywords', on_delete=models.deletion.CASCADE)


class Grade(models.Model):
    GRADE_CHOICES = zip(range(1, 6), range(1, 6))
    value = models.PositiveIntegerField(verbose_name='Grade', choices=GRADE_CHOICES)
    description = models.CharField(max_length=1024)
    innovation = models.ForeignKey(Innovation, related_name='grades', on_delete=models.deletion.CASCADE)
    user = models.ForeignKey(User, related_name='grades', on_delete=models.deletion.CASCADE)


class InnovationUrl(models.Model):
    class Meta:
        verbose_name = 'Innovation Url'
        verbose_name_plural = 'Innovation Urls'

    url = models.URLField()
    innovation = models.ForeignKey(Innovation, related_name='urls', on_delete=models.deletion.CASCADE)


class InnovationAttachment(models.Model):
    class Meta:
        verbose_name = 'Innovation Attachment'
        verbose_name_plural = 'Innovation Attachments'

    file = models.FileField(upload_to='attachments/', null=True)
    innovation = models.ForeignKey(Innovation, related_name='attachments', on_delete=models.deletion.CASCADE)

    @property
    def filename(self):
        return os.path.basename(self.file.name)


class ViolationReport(models.Model):
    substantiation = models.CharField(max_length=1024)
    creation_date = models.DateTimeField(auto_now_add=True)
    closing_date = models.DateTimeField(default=None, null=True, blank=True)
    issuer = models.ForeignKey(User, related_name="violation_reports", on_delete=models.deletion.CASCADE)
    innovation = models.ForeignKey(Innovation, related_name='violation_reports', on_delete=models.deletion.CASCADE)


class StatusVote(models.Model):
    innovation = models.ForeignKey(Innovation, related_name="status_votes", on_delete=models.deletion.CASCADE)
    user = models.ForeignKey(User, related_name="status_votes", on_delete=models.deletion.CASCADE)
    proposed_status = models.CharField(choices=Innovation.STATUS_CHOICES, max_length=32)
    substantiation = models.CharField(max_length=1024, verbose_name='Status Substantiation', null=True)


class InnovationComment(models.Model):
    text = models.CharField(max_length=4096)
    issuer = models.ForeignKey(User, related_name='innovation_comments', on_delete=models.deletion.CASCADE)
    innovation = models.ForeignKey(Innovation, related_name='innovation_comment', on_delete=models.deletion.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Time Added')

innovations/forms.py
from django import forms

from innovations.models import Innovation, ViolationReport, Grade, InnovationComment

# TODO: url i attachment powinny umożliwiać dodanie więcej niż jednego elementu
from innovations.status_flow import available_status_choices


class InnovationAddForm(forms.ModelForm):
    keywords = forms.CharField(max_length=2048)
    url = forms.URLField(required=False)
    attachment = forms.FileField(required=False)

    class Meta:
        model = Innovation
        fields = ['subject', 'description', 'assumptions', 'benefits', 'costs']


class StatusUpdateForm(forms.ModelForm):
    class Meta:
        model = Innovation
        fields = ['status', 'status_substantiation']


class ReportViolationForm(forms.ModelForm):
    class Meta:
        model = ViolationReport
        fields = ['substantiation']


class GradeForm(forms.ModelForm):
    value = forms.IntegerField(max_value=5, min_value=1)

    class Meta:
        model = Grade
        fields = ['value', 'description']


class WeightForm(forms.ModelForm):
    employee_grade_weight = forms.DecimalField(max_value=1, min_value=0, decimal_places=2)
    student_grade_weight = forms.DecimalField(max_value=1, min_value=0, decimal_places=2)

    class Meta:
        model = Innovation
        fields = ['student_grade_weight', 'employee_grade_weight']


class InnovationCommentForm(forms.ModelForm):
    text = forms.CharField(label='')

    class Meta:
        model = InnovationComment
        fields = ['text']

apsi_innovations/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db import transaction
from signup.groups import administrators, in_group, committee_members, in_groups, students, employees
from socials.models import Comment, SocialPost
from innovations.models import Innovation, Grade, InnovationComment


@login_required
def users(request):
    context = {
        'users': User.objects.all()
    }
    return render(request, "users.html", context)


@login_required
def admin_panel(request):
    if not has_admin_access(request.user):
        return render(request, "permission_denied.html")
    else:
        return render(request, "admin_panel.html")


@login_required
@transaction.atomic
def activate_user(request):
    if not has_admin_access(request.user):
        return render(request, "permission_denied.html")
    action = request.GET.get("action")
    user = User.objects.get(id=int(request.GET.get("id")))
    if user == request.user:
        return redirect("users")
    if action == "accept":
        user.is_active = True
        user.save()
    elif action == 'block':
        user.is_active = False
        user.save()
    return redirect("users")


@login_required
def student_employee_profile(request):
    if not in_groups(request.user, [students, employees]):
        return render(request, "permission_denied.html")
    return render(request, "student_employee_profile_view.html")


@login_required
@transaction.atomic
def activate_committee(request):
    if not has_admin_access(request.user):
        return render(request, "permission_denied.html")
    action = request.GET.get("action")
    user = User.objects.get(id=int(request.GET.get("id")))
    group = committee_members
    if action == "accept":
        user.groups.add(group)
        user.save()
    elif action == 'block':
        user.groups.remove(group)
        user.save()
    return redirect("users")


def has_admin_access(user):
    return in_group(user, administrators)

apsi_innovations/templates/innovations/details.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load user_tags %}
{% block content %}
    {% load innovation_tags %}

    {% if innovation %}

        {% if innovation.status == "blocked" and not request.user|has_group:"administrators" %}

            <h3>This idea has been blocked by an administrator.</h3>

        {% else %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-6">
                            <h4><a href={% url 'details' id=innovation.id %}>{{ innovation.subject }}</a></h4>
                        </div>
                        <div class="col-lg-6">
                            <button class="btn btn-sm pull-right">{{ innovation.status }}</button>
                        </div>
                    </div>

                </div>
                <div class="panel-body">
                    <p><h4>Description:</h4>
                    {{ innovation.description }} </p>
                    <p><h4>Assumptions:</h4>
                    {{ innovation.assumptions }} </p>
                    <p><h4>Benefits:</h4>
                    {{ innovation.benefits }} </p>
                    <p><h4>Cost:</h4>
                    {{ innovation.costs }} </p>
                    <p><h4>Grade:</h4>
                    {{ innovation.grade }} </p>

                    <p><h4>Keywords: </h4> </p>
                    {% for keyword in innovation.keywords.all %}
                        {{ keyword.keyword }}
                    {% endfor %}
                    {% if innovation.attachments.all %}

                        <p><h4>Links:</h4></p>
                        <p>
                            {% for attachment in innovation.urls.all %}
                                {% if attachment.url %}
                                    <a href='{{ attachment.url }}'>{{ attachment.url }}</a>
                                {% endif %}
                            {% endfor %}
                        </p>
                        <p><h4>Attachments: </h4> </p>
                        <p>
                            {% for attachment in innovation.attachments.all %}
                                {% if attachment.filename %}
                                    <a href='{{ attachment.file.url }}'
                                       class="btn btn-success">{{ attachment.filename }}</a>
                                {% endif %}
                            {% endfor %}
                        </p>
                        <p><b><h4>Grade:</h4>
                            {{ innovation.grade }} </b></p>

                    {% endif %}

                    {% if request.user|has_group:"administrators" %}
                        <p><h4>Student grade weight:</h4>
                        {{ innovation.student_grade_weight }} </p>
                        <p><h4>Committee grade weight:</h4>
                        {{ innovation.employee_grade_weight }} </p>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    {% if request.user|has_group:"administrators" and innovation|is_processing %}
                        <a href="{% url 'update_weights' id=innovation.id %}" class="btn btn-primary">CHANGE WEIGHTS</a>
                    {% endif %}
                    {% if innovation.status == "voting" or innovation.status == "in_replenishment" %}
                        {% if request.user|has_group:"students" and innovation.student_grade_weight or request.user|has_group:"committee_members" and innovation.employee_grade_weight %}
                            <a href="{% url 'rate' id=innovation.id %}"
                               class="btn btn-primary">RATE</a>
                        {% endif %}
                    {% endif %}
                    {% if not request.user|has_group:"administrators" %}
                        <a href="{% url 'report_violation' id=innovation.id %}" class="btn btn-primary">REPORT</a>
                    {% endif %}


                    {# ------------- ADMIN BUTTONS ---------------------#}
                    {% if request.user|has_group:"administrators" %}
                        {% if innovation.status != "blocked" %}
                            <a href="{% url 'update_status' id=innovation.id %}">
                                <button type="submit" class="btn btn-danger pull-right">Change status</button>
                            </a>
                        {% endif %}
                        {% if innovation.status == "pending" or innovation.status == "in_replenishment" %}
                            <a href="{% url 'set_status' id=innovation.id status="voting" %}">
                                <button type="submit" class="btn btn-danger pull-right">Start voting</button>
                            </a>
                        {% endif %}
                        {# TODO consider adding more fast set_status buttons. #}
                    {% endif %}
                </div>
                <div class="panel-footer">
                    {# ------------- COMMITTEE BUTTONS  / PANEL ---------------------#}
                    {% if request.user|has_group:"committee_members" %}
                        <div class="table-responsive">
                            <table class="table">

                                <tr>
                                    {% for header in status_votes_table.headers %}
                                        <td>{{ header }}</td>
                                    {% endfor %}
                                    <td>New substantiation</td>
                                </tr>
                                {% for row in status_votes_table.rows %}
                                    <tr>
                                        {% for value in row %}
                                            <td>{{ value }}</td>
                                        {% endfor %}
                                        <td>
                                            <form method="post" action={% url 'vote_status' id=innovation.id %}>
                                                {% csrf_token %}
                                                <input name="substantiation"/>
                                                <input name="status" hidden="hidden" value={{ row.0 }}  %}>
                                                <input type="submit" value="VOTE" class="btn btn-primary"/>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}


        <h3>Comments:</h3>
        <form action="{% url "innovation_comment" innovation.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|as_bootstrap }}
            <button type="submit" class="btn btn-primary">Add Comment!</button>
        </form>
        <br/>

        {% if innovation_comments %}
            {% for comment in innovation_comments %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{ comment.issuer }}
                        <p class="pull-right">
                            <small><i>{{ comment.timestamp }}</i></small>
                        </p>
                    </div>
                    <div class="panel-body">
                        {{ comment.text }}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No comments yet.</p>
        {% endif %}
        {% if comments %}
            <h3>Grade history:</h3>
            {% for grade in comments %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Grade: {{ grade.value }}
                    </div>
                    <div class="panel-body">
                        {{ grade.description }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}


    {% else %}
        <p>No innovation details.</p>
    {% endif %}
{% endblock %}

apsi_innovations/templates/innovations/innovations_home.html
{% extends 'base.html' %}
{% load user_tags %}
{% block content %}

    {% if request.user|has_group:"students" or request.user|has_group:"employees" %}
        <a href="/student_employee_profile/">MY PROFILE</a> <BR>
    {% endif %}

    {% if request.user|has_group:"committee_members" or request.user|has_group:"administrators" %}
        <a href="/innovations/reported_violations/">REPORTED VIOLATIONS</a> <BR>
        <a href="/innovations/innovations/?status=blocked">BLOCKED</a> <BR>
        <a href="/innovations/innovations/?status=suspended">SUSPENDED</a> <BR>
        <a href="/innovations/innovations/?status=in_replenishment">IN REPLENISHMENT</a> <BR>
    {% endif %}

    <a href="/innovations/innovations/?status=accepted">ACCEPTED</a> <BR>
    <a href="/innovations/innovations/?status=rejected">REJECTED</a> <BR>
    <a href="/innovations/innovations/?status=voting">IN VOTING</a> <BR>
    <a href="/innovations/my_innovations/">MY INNOVATIONS</a> <BR>
    <a href="/innovations/innovations/">ALL</a> <BR>

{% endblock %}

apsi_innovations/templates/innovations/innovations_list.html
{% extends 'base.html' %}
{% load user_tags %}
{% load innovation_tags %}
{% block content %}

    {% for innovation in innovation_list %}
        <div class="panel panel-default">
            <div class="panel-heading">
				<div class="row">
					<div class="col-lg-6">
							<h4><a href={% url 'details' id=innovation.id %}>{{ innovation.subject }}</a></h4>
					</div>
					<div class="col-lg-6">
							<button class="btn btn-sm pull-right">{{ innovation.status }}</button>
					</div>
				</div>
            </div>
            <div class="panel-body">
                <p>
                {{ innovation.description }}
				</p>
				{% if innovation.keywords.all %}
					<p>
						<b>Keywords:</b>
						{% for keyword in innovation.keywords.all %}
							{{ keyword.keyword }},
						{% endfor %}
					</p>
				{% endif %}
            </div>
                <div class="panel-footer">
			    {% if request.user|has_group:"administrators" and innovation|is_processing %}
                   <a href="{% url 'update_weights' id=innovation.id %}" class="btn btn-primary">CHANGE WEIGHTS</a>
                {% endif %}
		        </div>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.get_full_path|remove_page_arg }}&page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.get_full_path|remove_page_arg }}&page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

apsi_innovations/templates/innovations/rating.html
{% extends 'base.html' %}
{% load user_tags %}
{% load innovation_tags %}
{% load bootstrap_tags %}
{% block content %}

<h2>INNOVATION RATING</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

apsi_innovations/templates/innovations/report_violation.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|as_bootstrap}}
    <button type="submit" class="btn btn-primary">Send message</button>
  </form>
{% endblock %}

apsi_innovations/templates/innovations/reported_violations.html
{% extends 'base.html' %}
{% load user_tags %}
{% block content %}

    {% for violation in violations %}

        <div class="panel panel-default">
            <div class="panel-heading">
                <a href={% url 'details' id=violation.innovation.id %}>{{ violation.innovation.subject }}</a>
                <div class="btn btn-xs pull-right">{{ innovation.status }}</div>
            </div>
            <div class="panel-body">
                <p><h4>Substantiation of report:</h4>
                {{ violation.substantiation }} </p>
                <details>
                    <p><h4>Description:</h4>
                    {{ violation.innovation.description }} </p>
                    <p><h4>Assumptions:</h4>
                    {{ violation.innovation.assumptions }} </p>
                    <p><h4>Benefits:</h4>
                    {{ violation.innovation.benefits }} </p>
                    <p><h4>Cost:</h4>
                    {{ violation.innovation.costs }} </p>
                </details>
            </div>
            <div class="panel-footer">
                <a href="{% url 'finish_violation_report' %}?action=accept&id={{ violation.id }}">
                    <button type="submit" class="btn btn-danger pull-right">ACCEPT REPORT</button>
                </a>
                <a href="{% url 'finish_violation_report' %}?action=reject&id={{ violation.id }}">
                    <button type="submit" class="btn btn-danger pull-right">REJECT REPORT</button>
                </a>
            </div>

        </div>

    {% endfor %}

{% endblock %}

apsi_innovations/templates/innovations/update_status.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

apsi_innovations/templates/innovations/update_weights.html
{% extends 'base.html' %}
{% load user_tags %}
{% load innovation_tags %}
{% load bootstrap_tags %}
{% block content %}

<h2>INNOVATION UPDATE</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

apsi_innovations/templates/innovations/voting.html
{% extends 'base.html' %}
{% load user_tags %}
{% load innovation_tags %}
{% load bootstrap_tags %}
{% block content %}

<h2>INNOVATION VOTE</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form|as_bootstrap}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}